### ISSUE TITLE
Feature - The user shall be able to view the dashboard

### ISSUE THREAD

**Issue by NerdvanaConsulting** [NerdvanaConsulting/Vehicle-Management#5]
**FeatureDescription**
[Describe the feature using use case format.]

* Task-based sub-features:
- [ ] #6 Display the dashboard
- [ ] #7 Display dashboard navigation options
- [x] #12 Build route for dashboard
- [ ] Build models for dashboard

Please be sure to link the issue task back to this feature or issue)
