### ISSUE TITLE
Feature - The user shall be able to manage their vehicles

### ISSUE THREAD

**Issue by NerdvanaConsulting** [NerdvanaConsulting/Vehicle-Management#8]
**FeatureDescription**
The user shall be able to add, edit and display a list of their vehicles.

* Task-based sub-features:
- [x] #17 Build vehicle route (Client-Side)
- [x] #19 Model for vehicles (Client-Side)
- [ ] #20 Model for vehicles (Server-Side)
- [x] #24 Navigate to the Vehicle page
- [ ] Add a new vehicle
- [ ] Edit an existing vehicle
- [x] #18 View details about a vehicle
- [x] #24 View a list of vehicles
- [ ] Delete a vehicle from the list

Please be sure to link the issue task back to this feature or issue)
